"""Baseline

Revision ID: 9b0cb9a8992d
Revises: 
Create Date: 2026-01-13 08:52:20.952793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b0cb9a8992d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('document', sa.String(length=50), nullable=True),
    sa.Column('short_address', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_zones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('eav_attributes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('data_type', sa.String(length=30), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('price_per_unit', sa.Float(), nullable=False),
    sa.Column('price_affects', sa.Boolean(), nullable=False),
    sa.Column('extra_percent', sa.Float(), nullable=False),
    sa.Column('visible_expr', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('eav_product_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('impresiones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('costo_adicional', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('legacy_materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_sequences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('numero_orden', sa.String(length=50), nullable=False),
    sa.Column('articulo', sa.String(length=200), nullable=False),
    sa.Column('asesor', sa.String(length=120), nullable=False),
    sa.Column('venta_usd', sa.Float(), nullable=False),
    sa.Column('forma_pago', sa.String(length=80), nullable=True),
    sa.Column('serial_billete', sa.String(length=200), nullable=True),
    sa.Column('banco', sa.String(length=120), nullable=True),
    sa.Column('referencia', sa.String(length=120), nullable=True),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('monto_bs', sa.Float(), nullable=True),
    sa.Column('monto_usd_calculado', sa.Float(), nullable=True),
    sa.Column('tasa_bcv', sa.Float(), nullable=True),
    sa.Column('abono_usd', sa.Float(), nullable=True),
    sa.Column('restante', sa.Float(), nullable=True),
    sa.Column('iva', sa.Float(), nullable=True),
    sa.Column('diseno_usd', sa.Float(), nullable=True),
    sa.Column('delivery_usd', sa.Float(), nullable=True),
    sa.Column('ingresos_usd', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('cliente', sa.String(length=200), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=2000), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('total_bs', sa.Float(), nullable=True),
    sa.Column('details_json', sa.String(length=4000), nullable=True),
    sa.Column('commission_paid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_orden')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=150), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_table('tipo_talonarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('precio_base', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('transaction_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('eav_attribute_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('price_per_unit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['eav_attributes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eav_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['eav_product_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eav_type_attributes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['eav_attributes.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['eav_product_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('waste_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['legacy_materials.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('details_json', sa.String(length=4000), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=80), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('amount_bs', sa.Float(), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('bank', sa.String(length=120), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talonario_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tipo_talonario_id', sa.Integer(), nullable=False),
    sa.Column('impresion_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_total', sa.Float(), nullable=False),
    sa.Column('detalles_json', sa.String(length=4000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['impresion_id'], ['impresiones.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tipo_talonario_id'], ['tipo_talonarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('related_table', sa.String(length=50), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['transaction_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('default_role_id', sa.Integer(), nullable=True),
    sa.Column('monthly_goal', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['default_role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('accounts_payable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('supplier_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configurable_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('corporeo_forms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_date', sa.DateTime(), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.Column('total_sales', sa.Integer(), nullable=False),
    sa.Column('total_amount_usd', sa.Float(), nullable=False),
    sa.Column('total_amount_bs', sa.Float(), nullable=False),
    sa.Column('total_ingresos_usd', sa.Float(), nullable=False),
    sa.Column('report_status', sa.String(length=20), nullable=False),
    sa.Column('report_data_json', sa.String(length=10000), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_date')
    )
    op.create_table('delivery_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('amount_bs', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eav_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.String(length=500), nullable=True),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('subtotal_money', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['eav_attributes.id'], ),
    sa.ForeignKeyConstraint(['option_id'], ['eav_attribute_options.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['eav_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('details_json', sa.String(length=4000), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('designer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_method', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['designer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=True),
    sa.Column('size_text', sa.String(length=120), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('rol', sa.String(length=100), nullable=True),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=True),
    sa.Column('salario', sa.Float(), nullable=True),
    sa.Column('commission_pct', sa.Float(), nullable=False),
    sa.Column('bonus_attendance', sa.Float(), nullable=False),
    sa.Column('bonus_food', sa.Float(), nullable=False),
    sa.Column('bonus_role', sa.Float(), nullable=False),
    sa.Column('bank_account', sa.String(length=50), nullable=True),
    sa.Column('pago_movil_cedula', sa.String(length=20), nullable=True),
    sa.Column('pago_movil_phone', sa.String(length=20), nullable=True),
    sa.Column('pago_movil_bank', sa.String(length=100), nullable=True),
    sa.Column('binance_email', sa.String(length=200), nullable=True),
    sa.Column('zelle_email', sa.String(length=200), nullable=True),
    sa.Column('payment_frequency', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corporeo_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('order_number', sa.String(length=50), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('soporte_model_id', sa.Integer(), nullable=True),
    sa.Column('soporte_qty', sa.Integer(), nullable=True),
    sa.Column('luz_pv_id', sa.Integer(), nullable=True),
    sa.Column('luz_price', sa.Float(), nullable=True),
    sa.Column('posicion_luz', sa.String(length=128), nullable=True),
    sa.Column('precio_total_usd', sa.Float(), nullable=True),
    sa.Column('precio_total_bs', sa.Float(), nullable=True),
    sa.Column('payload_json', sa.String(length=10000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corporeo_payloads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('order_number', sa.String(length=50), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=300), nullable=True),
    sa.Column('descripcion_user', sa.String(length=2000), nullable=True),
    sa.Column('alto_cm', sa.Float(), nullable=True),
    sa.Column('ancho_cm', sa.Float(), nullable=True),
    sa.Column('diam_mm', sa.Float(), nullable=True),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('cortes_json', sa.String(length=2000), nullable=True),
    sa.Column('corte_combo_text', sa.String(length=200), nullable=True),
    sa.Column('material_label', sa.String(length=200), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('espesor_label', sa.String(length=200), nullable=True),
    sa.Column('espesor_id', sa.Integer(), nullable=True),
    sa.Column('espesor_price', sa.Float(), nullable=True),
    sa.Column('base_color', sa.String(length=200), nullable=True),
    sa.Column('base_color_code', sa.String(length=120), nullable=True),
    sa.Column('base_crudo', sa.Boolean(), nullable=True),
    sa.Column('base_transparente', sa.Boolean(), nullable=True),
    sa.Column('tipos_corporeo_json', sa.String(length=4000), nullable=True),
    sa.Column('soporte_model', sa.String(length=200), nullable=True),
    sa.Column('soporte_size', sa.String(length=200), nullable=True),
    sa.Column('soporte_price', sa.Float(), nullable=True),
    sa.Column('soporte_qty', sa.Integer(), nullable=True),
    sa.Column('luces_json', sa.String(length=2000), nullable=True),
    sa.Column('luz_color', sa.String(length=120), nullable=True),
    sa.Column('posicion_luz', sa.String(length=128), nullable=True),
    sa.Column('luz_pv_id', sa.Integer(), nullable=True),
    sa.Column('luz_price', sa.Float(), nullable=True),
    sa.Column('regulador_label', sa.String(length=120), nullable=True),
    sa.Column('regulador_id', sa.Integer(), nullable=True),
    sa.Column('regulador_price', sa.Float(), nullable=True),
    sa.Column('regulador_qty', sa.Integer(), nullable=True),
    sa.Column('caja_enabled', sa.Boolean(), nullable=True),
    sa.Column('caja_base', sa.String(length=120), nullable=True),
    sa.Column('caja_faja', sa.String(length=120), nullable=True),
    sa.Column('caja_pct', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('payload_json', sa.String(length=10000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('delivery_user_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_source', sa.String(length=50), nullable=True),
    sa.Column('amount_bs', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['delivery_payments.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['delivery_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_parameter_tables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('schema_json', sa.String(length=5000), nullable=False),
    sa.Column('has_auto_id', sa.Boolean(), nullable=False),
    sa.Column('parent_table_id', sa.Integer(), nullable=True),
    sa.Column('relationship_column', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_table_id'], ['product_parameter_tables.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['configurable_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker_goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('target_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_parameter_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parameter_table_id', sa.Integer(), nullable=False),
    sa.Column('row_data_json', sa.String(length=2000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parameter_table_id'], ['product_parameter_tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_parameter_values')
    op.drop_table('worker_goals')
    op.drop_table('product_parameter_tables')
    op.drop_table('deliveries')
    op.drop_table('corporeo_payloads')
    op.drop_table('corporeo_configs')
    op.drop_table('workers')
    op.drop_table('user_roles')
    op.drop_table('product_models')
    op.drop_table('orders')
    op.drop_table('eav_values')
    op.drop_table('delivery_payments')
    op.drop_table('daily_reports')
    op.drop_table('corporeo_forms')
    op.drop_table('configurable_products')
    op.drop_table('accounts_payable')
    op.drop_table('users')
    op.drop_table('transactions')
    op.drop_table('talonario_configs')
    op.drop_table('sale_payments')
    op.drop_table('sale_items')
    op.drop_table('role_permissions')
    op.drop_table('product_materials')
    op.drop_table('product_categories')
    op.drop_table('eav_type_attributes')
    op.drop_table('eav_products')
    op.drop_table('eav_attribute_options')
    op.drop_table('transaction_categories')
    op.drop_table('tipo_talonarios')
    op.drop_table('system_config')
    op.drop_table('suppliers')
    op.drop_table('sales')
    op.drop_table('roles')
    op.drop_table('products')
    op.drop_table('permissions')
    op.drop_table('order_sequences')
    op.drop_table('legacy_materials')
    op.drop_table('impresiones')
    op.drop_table('eav_product_types')
    op.drop_table('eav_attributes')
    op.drop_table('delivery_zones')
    op.drop_table('customers')
    op.drop_table('accounts')
    # ### end Alembic commands ###
